Ignore rspec-1 scenario on JRuby.
The load path change I made in the last commit broke the JRuby build:

java.io.IOException: Cannot run program "spec" (in directory "/home/vagrant/builds/myronmarston/vcr/tmp/aruba"): java.io.IOException: error=2, No such file or directory (NativeException)

I don't care enough to get this to pass.